model:
    debug_print_flag: False #Use 1 (True) to enable or 0 (False) to disable.
    weight_fn: None #True #False #TOTEST

dataset:
    github_data_path: "data/mobious/sample-frames/test640x400"
    # github_data_path: "data/mobious/sample-frames/test3000x1700"
    # data_path: "datasets/ready/mobious/MOBIOUS/train" #LOCAL
    data_path: "datasets/mobious/MOBIOUS/train" #SERVER
    models_path: "datasets/ready/mobious/models" #LOCAL and #SERVER paths
    checkpoint_path: "datasets/?"

model_hyperparameters:
    batch_size: 8
    num_workers: 4
    epochs: 100
    learning_rate: 0.003
