model:
    input_model_name: "_weights_10-09-24_04-50-40.pth"

dataset:
    models_path: "datasets/ready/mobious/models"
    github_data_path: "data/mobious"
    data_path: "datasets/ready/mobious/MOBIOUS"
    checkpoint_path: "datasets/?"
