---
site_name: ready
site_description: Documentation website for READY
site_author: READY Authors
copyright: Copyright © 2026 READY Authors
repo_url: https://github.com/oocular/ready/
repo_name: oocular/ready
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material
  features:
    - content.action.edit
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

nav:
  - Overview: index.md
  - API reference: api.md
  - License: LICENSE.md

markdown_extensions:
  - pymdownx.tasklist

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            show_submodules: true
          paths:
            - src
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
