[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[dependency-groups]
build = [
    "build",
]
dev = [
    "nox",
    "nox-uv",
    {include-group = "build"},
    {include-group = "lint"},
]
docs = [
    "mkdocstrings",
    "mkdocstrings-python",
    "zensical",
]
lint = [
    "prek",
]

[project]
name = "ready"
dynamic = ["version", "readme"]
requires-python = ">=3.12" #python=3.12 local  #python3.10 apptainer
keywords = ["AI"]
authors = [
  {name = "Miguel Xochicale", email = "add@email.com"},
  {name = "Add co-author", email = "add@email.com"},
]
maintainers = [
  {name = "Add maintener", email = "add@email.com"}
]
description = "Package example!"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
dependencies = [
    "numpy",
    "matplotlib",
    "pandas",
    "PyQt6",
    "loguru",
    "omegaconf",
    "scikit-learn",
    "pydot",
]
[project.optional-dependencies]
# development dependency groups
test = [
    "pytest",
    "pylint",
    "black",
    "isort",
    "codespell",
    "pre-commit"
]
learning = [
    "torch==2.13.0", #cricket PyTorch Version 2.3.0a0+6ddf5cf
    "torchvision==0.28.0",
]
model_optimisation = [
    "onnx==1.18.0",
    "onnxruntime==1.28.0",
    "onnxsim==0.7.1",
    "onnxscript==0.7.1",
    "onnx-ir==0.2.1",
    "onnx_graphsurgeon==0.3.27", # from https://pypi.ngc.nvidia.com
]

[[tool.uv.index]]
name = "nvidia-ngc"
url = "https://pypi.ngc.nvidia.com/"
explicit = true

[tool.uv.sources]
onnx-graphsurgeon = { index = "nvidia-ngc" }

[tool.setuptools.dynamic]
version = {attr = "ready.__version__"}
readme = {file = ["README.md"]}

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
include = ["ready"]  # package names should match these glob patterns (["*"] by default)
#exclude = ["my_package.tests*"]  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)
