%YAML 1.2
---
#Config template file for webrtc_ready.bash
workspace:
  rootPath: "/workspace/volumes/ready"
  apiPath: "/workspace/volumes/ready/src/ready/apis/holoscan/webrtc_ready"
  keysPath: "/workspace/volumes/datasets/ready/webrtc"

model:
  pathMap: "/workspace/volumes/datasets/ready/mobious/models_a10080gb/27-Jul-2025_03-44-52_NVIDIA_A100_80GB_PCI"
  name: "weights_27-Jul-2025_03-44-52-sim-BHWC.onnx"

recorder:
  # General variables
  loggername: "logger"
  loggerextension: ".log"
  videoWidth: "640"
  videoHeight: "400"
  videoChannels: "3"
  videoFrameRate: "30"
  cropVideoWidth: "520"
  cropVideoHeight: "300"
  crop_xpos: "50"
  crop_ypos: "40"

  # Patient_test_ID000
  directory: "/workspace/volumes/datasets/ready/webrtc/recordings/test_ID000"
  basename: "ID000_GAZETESTCENTRAL01_DEVICENAME_DATE_TIME"
  videoStartFrameTime: "4.5"
  videoEndFrameTime: "30.0"
