---
#Config file for ready_py.bash
workspace:
  apiPath: "/workspace/volumes/ready/src/ready/apis/holoscan/ready/python"
  configYamlPath: "/workspace/volumes/ready/configs/apis"
  configYamlFile: "config_readypy_yaml.yaml"

recorder:
  #PatientID001
  directory: "/workspace/volumes/datasets/ready/ready_py/recordings/test"
  loggername: "logger"
  loggerextension: ".log"
  basename: "ID001_GAZETESTCENTRAL01_logitechc930e_DATE_TIME"
  #basename: "ID001_GAZETESTLEFT02_logitechc930e_DATE_TIME"
  #basename: "ID001_GAZETESTRIGTH03_logitechc930e_DATE_TIME"
  #basename: "ID001_GAZETESTUP04_logitechc930e_DATE_TIME"
  #basename: "ID001_GAZETESTDOWN05_logitechc930e_DATE_TIME"
  #basename: "ID001_GAZETESTCENTRAL06_logitechc930e_DATE_TIME"

model:
  #
  #
  #TODO add args to __init__ in READYapp class
  #
  #
  width: 640
  height: 400
  ###################
  ##UNET with openEDS
  # video_path: "/workspace/volumes/datasets/ready/videos/openEDS"
  # model_path: "/workspace/volumes/datasets/ready/openEDS/models"
  # model_name: "model3ch-23jul2024t0716-sim-BHWC.onnx"
  # model_name: "_weights_10-09-24_23-53-45-sim-BHWC.onnx"
  ###################
  ## others
  #video_path: "/workspace/volumes/datasets/ready/videos/benign-positional-vertigo"
  #video_path: "/workspace/volumes/datasets/ready/videos/novel"
  #video_path: "/workspace/volumes/datasets/ready/videos/shared"
  video_path: "/workspace/volumes/datasets/ready/ready_py/recordings"
  ###################
  ##UNET with mobious
  # model_path: "/workspace/volumes/datasets/ready/mobious/models"
  # model_name: "_weights_10-09-24_06-35-14-sim-BHWC.onnx"
  # model_name: "_weights_15-12-24_07-00-10-sim-BHWC.onnx"
  model_path: "/workspace/volumes/datasets/ready/mobious/models_a10080gb/27-Jul-2025_03-44-52_NVIDIA_A100_80GB_PCI"
  model_name: "weights_27-Jul-2025_03-44-52-sim-BHWC.onnx"

replayer:
  #
  #
  # VideoStreamReplayer
  #
  #
  # https://github.com/nvidia-holoscan/holoscan-sdk/blob/main/include/holoscan/operators/video_stream_replayer/video_stream_replayer.hpp
  #
  #
  ########################
  ## OpenEDS from video_path: "/workspace/volumes/datasets/videos/openEDS"
  ### Single frames
  # basename: "video_30_duplicated_frames_of_val-000180-640wX400h_rgb_channels1"
  # basename: "video_30_duplicated_frames_of_val-000180-640wX400h_rgb_channels3"
  # basename: "video_30_duplicated_frames_of_val-000180-640wX400h_channels1"
  # basename: "video_30_duplicated_frames_of_val-000180-640wX400h_channels3"
  ## Various re-scaled frames
  # basename: "video_30_duplicated_frames_of_four-frames-in-one_channels3"
  # basename: "video_30_duplicated_frames_of_fractal-frames-in-one_channels3"
  ## Multiple frames
  # basename: "video_frames"
  ########################
  ## Novel from video_path: "/workspace/volumes/datasets/ready/videos/novel"
  # basename: "cut_video_640x400_7117d0"
  # basename: "cut_video_640x400_cc6b03"
  # basename: "cropped_cut_video_640x400_cc6b03"
  # basename: "cut_video_640x400_bf7bf0"
  # basename: "cropped_cut_video_640x400_bf7bf0"
  ########################
  ## Shared from video_path: "/workspace/volumes/datasets/ready/videos/shared"
  #basename: "video_640x400_Acute_VN_Left"
  basename: "cropped_video_640x400_Acute_VN_Left"
  ########################
  ## Welgampola from video_path: "/workspace/volumes/datasets/ready/videos/benign-positional-vertigo"
  # basename: "cropped_cut_video_640x400_video2-left-posterior-cupulolithiasis"
  ## Details
  frame_rate: 0.0 # as specified in timestamps
  realtime: True # default: true
  repeat: True # default: false
  count: 0 # default: 0 (no frame count restriction)


