%YAML 1.2
---
#Config template file for webrtc_ready.bash
workspace:
  rootPath: "/workspace/volumes/ready"
  apiPath: "/workspace/volumes/ready/src/ready/apis/holoscan/webrtc_ready"
  keysPath: "/workspace/volumes/datasets/ready/webrtc"

model:
  pathMap: "/workspace/volumes/datasets/ready/mobious/models_a10080gb/27-Jul-2025_03-44-52_NVIDIA_A100_80GB_PCI"
  name: "weights_27-Jul-2025_03-44-52-sim-BHWC.onnx"

recorder:
  # General variables
  loggername: "logger"
  loggerextension: ".log"
  #
  postProcessed: "TRUE"
  basenamePostProcessed: "_postprocessed"
  #
  videoSensorWidth: "640"
  videoSensorHeight: "480"
  videoSensorFrameRate: "30"
  videoWidth: "640"
  videoHeight: "400"
  videoChannels: "3"
  videoFrameRate: "30"
  cropVideoWidth: "520"
  cropVideoHeight: "300"
  crop_xpos: "50"
  crop_ypos: "40"

  # Patient_test_ID000
  directory: "/workspace/volumes/datasets/ready/webrtc/recordings/test_ID000"
  basename: "ID000_GAZETESTCENTRAL01_DEVICENAME_DATE_TIME"
  videoStartFrameTime: "4.5"
  videoEndFrameTime: "30.0"
  # basename: "ID000_GAZETESTLEFT02_DEVICENAME_DATE_TIME"
  # basename: "ID000_GAZETESTRIGTH03_DEVICENAME_DATE_TIME"
  # basename: "ID000_GAZETESTUP04_DEVICENAME_DATE_TIME"
  # basename: "ID000_GAZETESTDOWN05_DEVICENAME_DATE_TIME"
  # basename: "ID000_GAZETESTCENTRAL06_DEVICENAME_DATE_TIME"

  ##MOBILE_MODEL
  #basename: "mobileMODEL_date_time"

  ##PIXEL8
  #basename: "pixel8_date_time"

  ##PIXEL9
  #basename: "pixel9_date_time"
  #basename: "pixel9_5may2025_0843"
