---
#Config file for webrtc_ready.bash
workspace:
  apiPath: "/workspace/volumes/ready/src/ready/apis/holoscan/webrtc_ready"
  keysPath: "/workspace/volumes/datasets/ready/webrtc"

model:
  pathMap: "/workspace/volumes/datasets/ready/mobious/models_a10080gb/10-May-2025_18-09-20_NVIDIA_A100_80GB_PCI"
  name: "weights_10-May-2025_18-09-20-sim-BHWC.onnx"
  #
  # pathMap: "/workspace/volumes/datasets/ready/mobious/models_a10080gb/26-Apr-2025_19-40-01"
  # name: "_weights_26-Apr-2025_19-40-01-sim-BHWC.onnx"
  #
  # pathMap: "/workspace/volumes/datasets/ready/mobious/models_a10080gb/29-Mar-2025_16-23-29"
  # name: "_weights_29-Mar-2025_16-23-29-sim-BHWC.onnx"
  #
  # pathMap: "/workspace/volumes/datasets/ready/mobious/models_a10080gb/28-Mar-2025_15-25-07"
  # name: "_weights_28-Mar-2025_15-25-07-sim-BHWC.onnx"
  #
  # pathMap: "/workspace/volumes/datasets/ready/mobious/models_a10080gb/15-12-24"
  # name: "_weights_15-12-24_07-00-10-sim-BHWC.onnx"

recorder:
  directory: "/workspace/volumes/datasets/ready/webrtc/recordings"
  ##MOBILE_MODEL
  #basename: "mobile_date_time"
  ##PIXEL8
  #basename: "pixel8_date_time"
  ##PIXEL9
  #basename: "pixel9_date_time"
  basename: "pixel9_5may2025_0843"
