model:
    input_model_name: "_weights_03-Jan-2025_08-15-39.pth"

dataset:
    models_path: "datasets/ready/mobious/models/03-Jan-2025"
    github_data_path: "data/mobious"
    data_path: "datasets/ready/mobious/MOBIOUS"
    checkpoint_path: "datasets/?"

#model_hyperparameters:
#    batch_size: 8
#    num_workers: 4
#    image_size: 1
#    epochs: 100
#    learning_rate: 0.003

